Password protection cli review (#168)
* Password Protection CLI and Plugin

* Fix: CI Checksum failure

* Code Review Fixes

* Fix for lint failure

* Fix for lint failures

* go.sum update

* fix tests

* Code Review Fixes

* Code Review Fixes

* update master-key create command

* default to interactive password entry without echo
* show error for - if not piping stdin
* support direct passphrase entry on command-line
* output master key as table to be consistent foramt
* warn that the master key is not retrievable later
* update help to specify that - and @file.txt are supported

$ ./dist/confluent/darwin_amd64/confluent secret master-key create
Master Key Passphrase:

Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase giggity
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase -
Error: please pipe your passphrase over stdin

$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase -
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | Joa1p0SrSdS4XK3d2z5N+Q38vijW34k4oENXsPSTK4U= |
+------------+----------------------------------------------+

$ echo -n giggity > passphrase.txt
$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase @passphrase.txt
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

* Edits to secrets command

* Password Protection CLI and Plugin

* Fix: CI Checksum failure

* Code Review Fixes

* Fix for lint failure

* Fix for lint failures

* go.sum update

* fix tests

* Code Review Fixes

* Code Review Fixes

* update master-key create command

* default to interactive password entry without echo
* show error for - if not piping stdin
* support direct passphrase entry on command-line
* output master key as table to be consistent foramt
* warn that the master key is not retrievable later
* update help to specify that - and @file.txt are supported

$ ./dist/confluent/darwin_amd64/confluent secret master-key create
Master Key Passphrase:

Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase giggity
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase -
Error: please pipe your passphrase over stdin

$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase -
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | Joa1p0SrSdS4XK3d2z5N+Q38vijW34k4oENXsPSTK4U= |
+------------+----------------------------------------------+

$ echo -n giggity > passphrase.txt
$ ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase @passphrase.txt
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

* fix bug in reading from stdin pipe

* Additional changes for compliance with Security Provider

* return errors, don't swallow them

* refactor flag resolver to shared pkg

Cody-Rays-MBP15:cli cody$ ./dist/confluent/darwin_amd64/confluent secret master-key create
Master Key Passphrase:
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | y57iytOZRWqPJY8bCFuMEQ+2+v/XLFxiXNEAZh6NwDA= |
+------------+----------------------------------------------+
Cody-Rays-MBP15:cli cody$ ./dist/confluent/darwin_amd64/confluent secret master-key create
Master Key Passphrase:
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+
Cody-Rays-MBP15:cli cody$ ./dist/confluent/darwin_amd64/confluent secret master-key create
Master Key Passphrase:
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+
Cody-Rays-MBP15:cli cody$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create
Error: please specify '--passphrase -' if you intend to pipe your passphrase over stdin
Cody-Rays-MBP15:cli cody$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase -
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+
Cody-Rays-MBP15:cli cody$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase @passphrase.txt
Error: open passphrase.txt: no such file or directory
Cody-Rays-MBP15:cli cody$ echo -n giggity > passphrase.txt
Cody-Rays-MBP15:cli cody$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase @passphrase.txt
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+
Cody-Rays-MBP15:cli cody$ echo giggity | ./dist/confluent/darwin_amd64/confluent secret master-key create --passphrase giggity
Save the Master Key. It is not retrievable later.
+------------+----------------------------------------------+
| Master Key | 0TUpUd+9IVQvrIcY0SyDNCHTkQ3I0H9CVYSXFv0X1P4= |
+------------+----------------------------------------------+

* Code Review Fixes

*  Code Review Fixes + Additional TestCases

Test Cases
1.    Create New Master Key
a.    ValidTestCase: valid create master key
b.    InvalidTestCase: empty passphrase
2.    Encryption
a.    ValidTestCase: encrypt config file, create new dek
b.    InvalidTestCase: master key not set
c.    InvalidTestCase: invalid config file path
3.    Decryption
a.    ValidTestCase: Decrypt config file
b.    InvalidTestCase: Different master key for decryption
c.    InvalidTestCase: Corrupted encrypted data
d.    InvalidTestCase: Corrupted DEK
4.    Rotate Data Key
a.    ValidTestCase: Rotate dek
b.    InvalidTestCase: Rotate corrupted dek
c.    InvalidTestCase: Invalid master key

5.    Rotate Master Key
a.    ValidTestCase: Rotate MEK
b.    InvalidTestCase: Empty master key passphrase
c.    InvalidTestCase: New master key passphrase same as old master key passphrase
6.    Add Config
a.    ValidTestCase: Add new configs
7.    Update Config
a.    ValidTestCase: Update existing configs
b.    InvalidTestCase: Key not present in config file
8.    Remove Config
a.    ValidTestCase: Remove existing configs
b.    InvalidTestCase: Remove non existing config

* feedback

* Fix for Lint errors

*  Add --config for encrypt function

* Code Review Fixes

* Fix Lint failure

* Update periods

* Fix Merge failure

* teeny tiny fix so no panic on lint-cli

* comment out punctuation lint rules until we merge

* Code Review Fixes

* Code Review Fixes

* Code Review Fixes +  Disable auto expansion of properties

* Fix for build failure

* Code Review Fixes
- Maintain the order for Decrypt function
- Use just the config file name instead of fully qualified path in the key
- Error messages for failure
- Atomic operations for update/remove for partial key matches

* Code Review Fix: Rotate master key

* Fix for Lint failure

* Delete 1

* Code Review Fixes

* Code Review Fixes

* Code Review Fixes : Added require for checking errors and few additional test cases

* Code Review Fix: Random Number Generator for Testing

* replace switch with rng source interface

* Code Review Fixes : Test Added content based validation and error msgs validation

* Fix for Merge errors

* Code Review Fixes nit

* add coverage

* rename file

* fix

* Fix for merge with master reverted the prompt changes

* Code Review Fixes

* Fix for prompting passwords for Rotate command

* Fix for Add and Update commands to correctly handle \n in config params

* Code Review Fix